function geoip_country_code() { return 'IN'; }
function geoip_country_name() { return 'India'; }
function geoip_city()         { return 'Kochi'; }
function geoip_region()       { return '13'; }
function geoip_region_name()  { return 'Kerala'; }
function geoip_latitude()     { return '9.9667'; }
function geoip_longitude()    { return '76.2333'; }
function geoip_postal_code()  { return ''; }
function geoip_area_code()    { return ''; }
function geoip_metro_code()   { return ''; }
